
	/**
	 * Extrait le type MIME pour un fichier donné
	 * @param filename Le nom du fichier
	 * @return le type MIME
	 */
	@AutomatedTests(value = "source.txt", filenames = 0)
	@AutomatedTests(value = "OutilsCommun")
	@StrictAutomatedTests({ "OutilsCommun", "c2VjcmV0S2V5" }) // secretKey -> Base64("secretKey")
	@StrictAutomatedTests({ "aVnxqL186Sz1t4MpodYomg==", "c2VjcmV0S2V5" }) // encryptedText -> encrypt("OutilsCommun", Base64("secretKey"))
	final public static String getMIME(String filename) {
		if (!isEmpty(filename)) {
			File file = new File(filename);

			if (file.exists()) {
				try {
					String type = Files.probeContentType(file.toPath());

					if (!isEmpty(type)) {
						return type;
					}
				} catch (IOException e) {
					// ignore...
					e.printStackTrace();
				}
			}

			String ext = filename.toLowerCase();

			int pos = ext.lastIndexOf(".");

			if (pos != -1) {
				ext = ext.substring(pos + 1);

				switch (ext) {
					case "pyc":
						return "applicaiton/x-bytecode.python";
					case "dwg":
						return "application/acad";
					case "arj":
						return "application/arj";
					case "mm":
					case "mme":
						return "application/base64";
					case "hqx":
						return "application/binhex";
					case "boo":
					case "book":
						return "application/book";
					case "ccad":
						return "application/clariscad";
					case "dp":
						return "application/commonground";
					case "drw":
						return "application/drafting";
					case "tsp":
						return "application/dsptype";
					case "xl":
					case "xla":
					case "xlb":
					case "xlc":
					case "xld":
					case "xlk":
					case "xll":
					case "xlm":
					case "xls":
					case "xlt":
					case "xlv":
					case "xlw":
						return "application/excel";
					case "frl":
						return "application/freeloader";
					case "spl":
						return "application/futuresplash";
					case "vew":
						return "application/groupwise";
					case "hta":
						return "application/hta";
					case "unv":
						return "application/i-deas";
					case "inf":
						return "application/inf";
					case "class":
						return "application/java";
					case "mrc":
						return "application/marc";
					case "mbd":
						return "application/mbedlet";
					case "aps":
						return "application/mime";
					case "pot":
					case "pps":
					case "ppt":
					case "ppz":
						return "application/mspowerpoint";
					case "doc":
					case "dot":
					case "w6w":
					case "wiz":
					case "word":
						return "application/msword";
					case "wri":
						return "application/mswrite";
					case "mcp":
						return "application/netmc";
					case "a":
					case "arc":
					case "com":
					case "dump":
					case "exe":
					case "o":
					case "psd":
					case "saveme":
					case "zoo":
						return "application/octet-stream";
					case "oda":
						return "application/oda";
					case "pdf":
						return "application/pdf";
					case "p7s":
						return "application/pkcs7-signature";
					case "crl":
						return "application/pkix-crl";
					case "ai":
					case "eps":
					case "ps":
						return "application/postscript";
					case "part":
					case "prt":
						return "application/pro_eng";
					case "rng":
						return "application/ringing-tones";
					case "set":
						return "application/set";
					case "smi":
					case "smil":
						return "application/smil";
					case "sol":
						return "application/solids";
					case "sdr":
						return "application/sounder";
					case "step":
					case "stp":
						return "application/step";
					case "ssm":
						return "application/streamingmedia";
					case "vda":
						return "application/vda";
					case "fdf":
						return "application/vnd.fdf";
					case "hgl":
					case "hpg":
					case "hpgl":
						return "application/vnd.hp-hpgl";
					case "sst":
						return "application/vnd.ms-pki.certstore";
					case "pko":
						return "application/vnd.ms-pki.pko";
					case "cat":
						return "application/vnd.ms-pki.seccat";
					case "ppa":
					case "pwz":
						return "application/vnd.ms-powerpoint";
					case "mpp":
						return "application/vnd.ms-project";
					case "ncm":
						return "application/vnd.nokia.configuration-message";
					case "rnx":
						return "application/vnd.rn-realplayer";
					case "wmlc":
						return "application/vnd.wap.wmlc";
					case "wmlsc":
						return "application/vnd.wap.wmlscriptc";
					case "web":
						return "application/vnd.xara";
					case "vmd":
						return "application/vocaltec-media-desc";
					case "vmf":
						return "application/vocaltec-media-file";
					case "wp":
					case "wp5":
					case "wp6":
					case "wpd":
						return "application/wordperfect";
					case "w60":
						return "application/wordperfect6.0";
					case "w61":
						return "application/wordperfect6.1";
					case "wk1":
						return "application/x-123";
					case "aim":
						return "application/x-aim";
					case "aab":
						return "application/x-authorware-bin";
					case "aam":
						return "application/x-authorware-map";
					case "aas":
						return "application/x-authorware-seg";
					case "bcpio":
						return "application/x-bcpio";
					case "bin":
						return "application/x-binary";
					case "bsh":
						return "application/x-bsh";
					case "bz":
						return "application/x-bzip";
					case "boz":
					case "bz2":
						return "application/x-bzip2";
					case "cdf":
						return "application/x-cdf";
					case "vcd":
						return "application/x-cdlink";
					case "cha":
					case "chat":
						return "application/x-chat";
					case "cco":
						return "application/x-cocoa";
					case "tgz":
					case "z":
					case "zip":
						return "application/x-compressed";
					case "nsc":
						return "application/x-conference";
					case "cpio":
						return "application/x-cpio";
					case "cpt":
						return "application/x-cpt";
					case "csh":
						return "application/x-csh";
					case "deepv":
						return "application/x-deepv";
					case "dcr":
					case "dir":
					case "dxr":
						return "application/x-director";
					case "dvi":
						return "application/x-dvi";
					case "elc":
						return "application/x-elc";
					case "env":
					case "evy":
						return "application/x-envoy";
					case "es":
						return "application/x-esrehber";
					case "pre":
						return "application/x-freelance";
					case "gsp":
						return "application/x-gsp";
					case "gss":
						return "application/x-gss";
					case "gtar":
						return "application/x-gtar";
					case "gz":
					case "gzip":
						return "application/x-gzip";
					case "hdf":
						return "application/x-hdf";
					case "help":
						return "application/x-helpfile";
					case "imap":
						return "application/x-httpd-imap";
					case "ima":
						return "application/x-ima";
					case "ins":
						return "application/x-internett-signup";
					case "iv":
						return "application/x-inventor";
					case "ip":
						return "application/x-ip2";
					case "jcm":
						return "application/x-java-commerce";
					case "js":
						return "application/x-javascript";
					case "skd":
					case "skm":
					case "skp":
					case "skt":
						return "application/x-koan";
					case "ksh":
						return "application/x-ksh";
					case "latex":
					case "ltx":
						return "application/x-latex";
					case "lha":
						return "application/x-lha";
					case "lsp":
						return "application/x-lisp";
					case "ivy":
						return "application/x-livescreen";
					case "wq1":
						return "application/x-lotus";
					case "lzh":
						return "application/x-lzh";
					case "lzx":
						return "application/x-lzx";
					case "mc$":
						return "application/x-magic-cap-package-1.0";
					case "mcd":
						return "application/x-mathcad";
					case "mif":
						return "application/x-mif";
					case "nix":
						return "application/x-mix-transfer";
					case "ani":
						return "application/x-navi-animation";
					case "nvd":
						return "application/x-navidoc";
					case "map":
						return "application/x-navimap";
					case "stl":
						return "application/x-navistyle";
					case "nc":
						return "application/x-netcdf";
					case "pkg":
						return "application/x-newton-compatible-pkg";
					case "aos":
						return "application/x-nokia-9000-communicator-add-on-software";
					case "omc":
						return "application/x-omc";
					case "omcd":
						return "application/x-omcdatamaker";
					case "omcr":
						return "application/x-omcregerator";
					case "pm4":
					case "pm5":
						return "application/x-pagemaker";
					case "pcl":
						return "application/x-pcl";
					case "plx":
						return "application/x-pixclscript";
					case "p10":
						return "application/x-pkcs10";
					case "p12":
						return "application/x-pkcs12";
					case "p7r":
						return "application/x-pkcs7-certreqresp";
					case "p7c":
					case "p7m":
						return "application/x-pkcs7-mime";
					case "p7a":
						return "application/x-pkcs7-signature";
					case "mpc":
					case "mpt":
					case "mpv":
					case "mpx":
						return "application/x-project";
					case "wb1":
						return "application/x-qpro";
					case "sdp":
						return "application/x-sdp";
					case "sea":
						return "application/x-sea";
					case "sl":
						return "application/x-seelogo";
					case "sh":
						return "application/x-sh";
					case "shar":
						return "application/x-shar";
					case "swf":
						return "application/x-shockwave-flash";
					case "spr":
					case "sprite":
						return "application/x-sprite";
					case "sit":
						return "application/x-stuffit";
					case "sv4cpio":
						return "application/x-sv4cpio";
					case "sv4crc":
						return "application/x-sv4crc";
					case "tar":
						return "application/x-tar";
					case "sbk":
					case "tbk":
						return "application/x-tbook";
					case "tex":
						return "application/x-tex";
					case "texi":
					case "texinfo":
						return "application/x-texinfo";
					case "roff":
					case "t":
					case "tr":
						return "application/x-troff";
					case "man":
						return "application/x-troff-man";
					case "me":
						return "application/x-troff-me";
					case "ms":
						return "application/x-troff-ms";
					case "ustar":
						return "application/x-ustar";
					case "vsd":
					case "vst":
					case "vsw":
						return "application/x-visio";
					case "mzz":
						return "application/x-vnd.audioexplosion.mzz";
					case "xpix":
						return "application/x-vnd.ls-xpix";
					case "src":
					case "wsrc":
						return "application/x-wais-source";
					case "hlp":
						return "application/x-winhelp";
					case "wtk":
						return "application/x-wintalk";
					case "svr":
						return "application/x-world";
					case "cer":
					case "crt":
					case "der":
						return "application/x-x509-ca-cert";
					case "snd":
						return "audio/basic";
					case "it":
						return "audio/it";
					case "funk":
					case "my":
					case "pfunk":
						return "audio/make";
					case "rmi":
						return "audio/mid";
					case "kar":
					case "mid":
					case "midi":
						return "audio/midi";
					case "m2a":
					case "mp2":
					case "mpa":
					case "mpga":
						return "audio/mpeg";
					case "mp3":
						return "audio/mpeg3";
					case "s3m":
						return "audio/s3m";
					case "tsi":
						return "audio/tsp-audio";
					case "qcp":
						return "audio/vnd.qcelp";
					case "voc":
						return "audio/voc";
					case "vox":
						return "audio/voxware";
					case "wav":
						return "audio/wav";
					case "aif":
					case "aifc":
					case "aiff":
						return "audio/x-aiff";
					case "au":
						return "audio/x-au";
					case "gsd":
					case "gsm":
						return "audio/x-gsm";
					case "jam":
						return "audio/x-jam";
					case "lam":
						return "audio/x-liveaudio";
					case "mod":
						return "audio/x-mod";
					case "m3u":
						return "audio/x-mpequrl";
					case "la":
					case "lma":
						return "audio/x-nspaudio";
					case "ram":
					case "rm":
					case "rmm":
					case "rmp":
						return "audio/x-pn-realaudio";
					case "rpm":
						return "audio/x-pn-realaudio-plugin";
					case "sid":
						return "audio/x-psid";
					case "ra":
						return "audio/x-realaudio";
					case "vqf":
						return "audio/x-twinvq";
					case "vqe":
					case "vql":
						return "audio/x-twinvq-plugin";
					case "mjf":
						return "audio/x-vnd.audioexplosion.mjuicemediafile";
					case "xm":
						return "audio/xm";
					case "pdb":
					case "xyz":
						return "chemical/x-pdb";
					case "ivr":
						return "i-world/i-vrml";
					case "bm":
					case "bmp":
						return "image/bmp";
					case "ras":
					case "rast":
						return "image/cmu-raster";
					case "fif":
						return "image/fif";
					case "flo":
					case "turbot":
						return "image/florian";
					case "g3":
						return "image/g3fax";
					case "gif":
						return "image/gif";
					case "ief":
					case "iefs":
						return "image/ief";
					case "jfif":
					case "jfif-tbnl":
					case "jpe":
					case "jpeg":
					case "jpg":
						return "image/jpeg";
					case "jut":
						return "image/jutvision";
					case "nap":
					case "naplps":
						return "image/naplps";
					case "pic":
					case "pict":
						return "image/pict";
					case "png":
					case "x-png":
						return "image/png";
					case "tif":
					case "tiff":
						return "image/tiff";
					case "fpx":
						return "image/vnd.fpx";
					case "rf":
						return "image/vnd.rn-realflash";
					case "rp":
						return "image/vnd.rn-realpix";
					case "wbmp":
						return "image/vnd.wap.wbmp";
					case "xif":
						return "image/vnd.xiff";
					case "dxf":
					case "svf":
						return "image/x-dwg";
					case "ico":
						return "image/x-icon";
					case "art":
						return "image/x-jg";
					case "jps":
						return "image/x-jps";
					case "nif":
					case "niff":
						return "image/x-niff";
					case "pcx":
						return "image/x-pcx";
					case "pct":
						return "image/x-pict";
					case "pnm":
						return "image/x-portable-anymap";
					case "pbm":
						return "image/x-portable-bitmap";
					case "pgm":
						return "image/x-portable-graymap";
					case "ppm":
						return "image/x-portable-pixmap";
					case "qif":
					case "qti":
					case "qtif":
						return "image/x-quicktime";
					case "rgb":
						return "image/x-rgb";
					case "xwd":
						return "image/x-xwd";
					case "xbm":
						return "image/xbm";
					case "xpm":
						return "image/xpm";
					case "mht":
					case "mhtml":
						return "message/rfc822";
					case "iges":
					case "igs":
						return "model/iges";
					case "dwf":
						return "model/vnd.dwf";
					case "vrml":
					case "wrl":
					case "wrz":
						return "model/vrml";
					case "pov":
						return "model/x-pov";
					case "pvu":
						return "paleovu/x-pv";
					case "css":
						return "text/css";
					case "acgi":
					case "htm":
					case "html":
					case "htmls":
					case "htx":
					case "shtml":
						return "text/html";
					case "asm":
					case "asp":
					case "c":
					case "c++":
					case "cc":
					case "conf":
					case "cpp":
					case "cxx":
					case "def":
					case "el":
					case "etx":
					case "f":
					case "f77":
					case "f90":
					case "for":
					case "g":
					case "h":
					case "hh":
					case "hlb":
					case "idc":
					case "jav":
					case "java":
					case "list":
					case "log":
					case "lst":
					case "m":
					case "mar":
					case "mcf":
					case "p":
					case "pas":
					case "pl":
					case "pm":
					case "py":
					case "rexx":
					case "s":
					case "sdml":
					case "tcl":
					case "tcsh":
					case "text":
					case "txt":
					case "zsh":
						return "text/plain";
					case "rt":
					case "rtf":
					case "rtx":
						return "text/richtext";
					case "wsc":
						return "text/scriplet";
					case "tsv":
						return "text/tab-separated-values";
					case "uni":
					case "unis":
					case "uri":
					case "uris":
						return "text/uri-list";
					case "abc":
						return "text/vnd.abc";
					case "flx":
						return "text/vnd.fmi.flexstor";
					case "wml":
						return "text/vnd.wap.wml";
					case "wmls":
						return "text/vnd.wap.wmlscript";
					case "htt":
						return "text/webviewhtml";
					case "aip":
						return "text/x-audiosoft-intra";
					case "htc":
						return "text/x-component";
					case "lsx":
						return "text/x-la-asf";
					case "ssi":
						return "text/x-server-parsed-html";
					case "sgm":
					case "sgml":
						return "text/x-sgml";
					case "spc":
					case "talk":
						return "text/x-speech";
					case "uil":
						return "text/x-uil";
					case "uu":
					case "uue":
						return "text/x-uuencode";
					case "vcs":
						return "text/x-vcalendar";
					case "xml":
						return "text/xml";
					case "afl":
						return "video/animaflex";
					case "avi":
						return "video/avi";
					case "avs":
						return "video/avs-video";
					case "dl":
						return "video/dl";
					case "fli":
						return "video/fli";
					case "gl":
						return "video/gl";
					case "mp4":
						return "video/mp4";
					case "m1v":
					case "m2v":
					case "mpe":
					case "mpeg":
					case "mpg":
						return "video/mpeg";
					case "moov":
					case "mov":
					case "qt":
						return "video/quicktime";
					case "vdo":
						return "video/vdo";
					case "viv":
					case "vivo":
						return "video/vivo";
					case "rv":
						return "video/vnd.rn-realvideo";
					case "vos":
						return "video/vosaic";
					case "xdr":
						return "video/x-amt-demorun";
					case "xsr":
						return "video/x-amt-showrun";
					case "fmf":
						return "video/x-atomic3d-feature";
					case "dif":
					case "dv":
						return "video/x-dv";
					case "isu":
						return "video/x-isvideo";
					case "mjpg":
						return "video/x-motion-jpeg";
					case "asf":
					case "asx":
						return "video/x-ms-asf";
					case "qtc":
						return "video/x-qtc";
					case "scm":
						return "video/x-scm";
					case "movie":
					case "mv":
						return "video/x-sgi-movie";
					case "wmf":
						return "windows/metafile";
					case "mime":
						return "www/mime";
					case "ice":
						return "x-conference/x-cooltalk";
					case "3dmf":
					case "qd3":
					case "qd3d":
						return "x-world/x-3dmf";
					case "vrt":
						return "x-world/x-vrt";
					case "xgz":
						return "xgl/drawing";
					case "xmz":
						return "xgl/movie";
				}
			}
		}

		return "application/octet-stream";
	}
